### ISSUE TITLE
PA - Review User Auth

### ISSUE THREAD

**Issue by zzachsmith** [zzachsmith/DogHousebnb#2]
- [x] New Account Creation

- [x] Login

- [x] Guest/Demo Login

- [x] Styling

**Comment by wongshington** [comment]
are you going to keep using the color(#FF6B7A) that you use for the signup/login buttons all around your site, because if so then you should try and make ur logo that color and also use that color for the "Doghouse BnB" portion of the session modal
- [ ] don't need the bullet points for the errors
- [ ] make the font size for "Welcome to DoghouseBnB" bigger, also add an "!". people love excitement
- [ ] center the text that you type in the input fields
- [ ] you're getting a weird "push" error when you log in, so try and squash that bug

**Comment by zzachsmith** [comment]
Yes I will have to change the logo to that color but i'm unsure how to do that since it's an image.

I like the Welcome to DoghouseBnB in the modal being #484848.

I solved all the bugs mentioned.

I kinda liked the bullet point errors though, thoughts?

**Comment by wongshington** [comment]
- [ ] nav bar moves down when you log out
for the logo, it might be a quick photoshop fix or if you can find a .svg image you can edit it in css(not part of user auth, but just a thought)
- lets revisit the error bullet points later. not too worried about it

**Comment by zzachsmith** [comment]
please review
